name: Bruin Sports Analytics
author: Bruin Sports Analytics
twitter: bruinanalytics

permalink: "/:title"

paginate: 10
paginate_path: "/page:num"

plugins:
  - jekyll-paginate



excerpt_separator: <!-- end excerpt here -->
